### ISSUE TITLE
Harrison road map

### ISSUE THREAD

**Issue by julietezekwe** [julietezekwe/roadmap#1]
- [x] Create an issue for the roadmap
- [ ] Project management
    - [x] Workflow definitions ~ [best practices](https://raygun.com/blog/git-workflow/), [tutorial](
https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
    - [ ] Coding conventions and style guides definition
    - [ ] Tasks creation on project management tool
- [ ] Setup
    - [ ] Version control system set up
    - [ ] Project management system setup
    - [ ] Stack selection for the learning period
    - [ ] Work environments and tools selection
    - [ ] Project setup on version control system
    - [ ] Tools setup
    - [ ] Project setup on local environments
    - [ ] Project structure setup
    - [ ] Test environment setup
- [ ] Project
    - [ ] Project selection 
    - [ ] Building the project following the stated rules
    - [ ] Code reviews
    - [ ] Continuous integrations setup
    - [ ] Continuous deployment setup
